server:
  port: 8007
eureka:
  instance:
    hostname: eureka8007
  client:
    register-with-eureka: false
    fetch-registry: false
    serviceUrl:
      defaultZone: http://192.168.88.159:8005/eureka/,http://192.168.88.159:8006/eureka/,http://192.168.88.159:8008/eureka/
